最終課題の提出
kawasaki8108/RaiseTech pull request #19
Opened 2024-06-18 10:01 UTC by kawasaki8108

README内でlecture13.mdへのリンクを付けていますが、mainにマージしたら有効になりますので、ご理解ください。

2024-06-18 14:47 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-06-18 14:47 UTC, MasatoshiMizumoto commented on image_14/circleci-cfn-ansible-serverspecのインフラ構成図(白背景).png
一部AWSアイコンで置換えできそうなもの（SSH Key→Azureアイコンかもしれない）や、旧世代のAWSアイコンぽいもの（Internet）がありますので、これを修正ください！

2024-06-19 02:03 UTC, kawasaki8108 commented on image_14/circleci-cfn-ansible-serverspecのインフラ構成図(白背景).png
Ansible,CircleCIも新しいのがあったのでInternetのアイコンと、あせて更新しました！SSHは普通の文字にしました！

2024-06-19 02:07 UTC, kawasaki8108 commented
アイコンの件、対応しました！ご確認をお願いいたします。

2024-06-19 02:33 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-06-19 02:33 UTC, MasatoshiMizumoto commented on image_14/circleci-cfn-ansible-serverspecのインフラ構成図(白背景).png
Internetまだ古いので、確認してほしいです！
AWSが提供する汎用アイコンで最新のものは線画が基本です！

2024-06-19 03:15 UTC, kawasaki8108 commented
すみません、理解しました！更新しました！よろしくお願いいたします。

2024-06-19 03:35 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-06-19 03:54 UTC, merged